### ISSUE TITLE
[Naad] Create add new invoice button and flow

### ISSUE THREAD

**Issue by AwesomeSam9523** [AwesomeSam9523/expense-tracker#24]

**Comment by last-brain-cell** [comment]
Added a component called AddButton with text and route props so that it can be used for "add new event as well as "add new invoice" and any such requirement in the future. Have made the necessary changes and tested on local. Will push code to another branch shortly.

**Comment by last-brain-cell** [comment]
could you elaborate on the flow thing, does it mean making navigation for the application for all possible pages and routes?

**Comment by AwesomeSam9523** [comment]
> could you elaborate on the flow thing, does it mean making navigation for the application for all possible pages and routes?


It is just making a new page `create-invoice` with the budget and image picker, and clicking submit will upload it to the server.
Similar code as `create-event`

**Comment by last-brain-cell** [comment]
> > could you elaborate on the flow thing, does it mean making navigation for the application for all possible pages and routes?
> 
> It is just making a new page `create-invoice` with the budget and image picker, and clicking submit will upload it to the server. Similar code as `create-event`

alright cool
